---
- name: install packages for web
  sudo: yes
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - libapache2-mod-php5
    - php5-intl

- name: ensure that apache is running
  service: name=apache2 state=started

- name: enable needed modes in apache
  sudo: yes
  command: a2enmod {{ item }}
  with_items:
    - rewrite
    - php5
  notify:
    - restart apache

- name: prepare site "{{ site_name }}" config for apache
  sudo: yes
  template: src=apache-config.j2 dest=/etc/apache2/sites-available/{{ site_name }}.conf owner=root group=root mode=644
  notify:
    - restart apache

- name: enable site in apache
  sudo: yes
  command: a2ensite {{ site_name }}
  notify:
    - restart apache